home: # http://tap.rubyforge.org
versions:
  configurable: 0.6.0
  lazydoc: 1.0.0
  rap: 0.15.0
  tap: 0.19.0
  tap-gen: 0.3.1
  tap-server: 0.6.0
  tap-suite: 0.3.0
  tap-tasks: 0.5.0
  tap-test: 0.3.0

links:
  # about me
  me: http://www.linkedin.com/in/simonachiang
  twitter: http://twitter.com/bahuvrihi
  blog: http://bahuvrihi.wordpress.com
  
  # code
  rubyforge: http://rubyforge.org/projects/tap
  github: http://github.com/bahuvrihi/tap
  google-group: http://groups.google.com/group/ruby-on-tap
  issues: http://github.com/bahuvrihi/tap/issues
  rdoc: http://tap.rubyforge.org/rdoc/index.html
  
  # gems
  tap: http://rubyforge.org/projects/tap
  configurable: http://tap.rubyforge.org/configurable
  lazydoc: http://tap.rubyforge.org/lazydoc
  external: http://rubyforge.org/projects/external
  constants: http://bioactive.rubyforge.org/constants
  molecules: http://bioactive.rubyforge.org/molecules
    
  # site
  install: /installation.html
  license: /license.html
  tutorial: /tutorial.html
  
  # external
  ucdenver: http://www.ucdenver.edu
  hansen_lab: http://hsc-proteomics.uchsc.edu/hansenlab/
  bmsp: http://biomol.uchsc.edu/
  rake: http://rake.rubyforge.org/
  rack: http://rack.rubyforge.org/
  rails: http://www.rubyonrails.org
  ruby: http://www.ruby-lang.org/en/
  ruby-download: http://www.ruby-lang.org/en/downloads/
  installer: 
    osx: http://rubyosx.rubyforge.org/
    windows: http://rubyinstaller.rubyforge.org/wiki/wiki.pl?RubyInstaller
  rubygems: http://www.rubygems.org/
  